Support for lossless audio (flac) in hls
kaltura/nginx-vod-module pull request #1219
Opened 2020-11-18 15:26 UTC by jotair

As apple now supports lossless audio (flac) in hls this pull adds this support mentioned in these issues

#1192 #1161

We tested these changes in VLC and iOS / tvOS 14 devices with the default avFramework / avPlayer

2020-11-18 15:30 UTC, kaltura-hooks commented
Hi @jotair,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

2020-12-13 19:49 UTC, erankor requested changes

2020-12-13 19:49 UTC, erankor commented on vod/codec_config.c
>  	default:
please retain the newline separate between cases/default

2020-12-13 19:49 UTC, erankor commented on vod/media_format.h
>  	// captions
again, please keep the newline separator between the different types of codes

2020-12-13 19:49 UTC, erankor commented on vod/mp4/mp4_parser.c
> +                        break;
please fix the indent, need to use tabs here

2020-12-14 13:45 UTC, merged

2020-12-14 13:45 UTC, erankor commented
merged, thanks!