FFmpeg: replace deprecated av_init_packet API
kaltura/nginx-vod-module pull request #1284
Opened 2021-06-18 21:30 UTC by JoelLinn

`sizeof(AVPacket)` being a part of the public FFmpeg ABI is deprecated.
https://ffmpeg.org/doxygen/trunk/structAVPacket.html

This patch fixes building against FFmpeg 4.4 with `-Werror`
Due to my use case I am limited in testing this thoroughly though :/

2021-06-19 07:51 UTC, JoelLinn commented
Fixes #1262 
@erankor

2021-06-22 08:39 UTC, erankor requested changes
Looks good, please check the couple of leaks that I mentioned.

2021-06-22 08:39 UTC, erankor commented on vod/filters/audio_encoder.c
>  	{
missing free here?

2021-06-22 08:39 UTC, erankor commented on vod/filters/audio_encoder.c
>  			return VOD_UNEXPECTED;
missing free?

2021-06-22 09:50 UTC, JoelLinn commented
Good catches!
I added the two frees

2021-07-01 10:00 UTC, rhummelmose commented
Lgtm :)

2021-07-07 08:42 UTC, r4fek commented
Looks like all issues were resolved. Can we merge this PR?

2021-07-07 12:45 UTC, rhummelmose commented
Maybe @erankor is on summer vacay :)

2021-07-12 08:30 UTC, merged

2021-07-12 08:30 UTC, erankor commented
Merged, thanks!