Initial draft: HLS playlistType event
kaltura/nginx-vod-module pull request #1289
Opened 2021-06-29 07:12 UTC by rhummelmose

Draft implementation as discussed in #1265

2021-06-29 07:14 UTC, rhummelmose commented
@erankor I've verified that this works in HLS.js, but VLC for instance won't let me rewind. I'm thinking it might be a VLC limitation though: https://trac.videolan.org/vlc/ticket/15994

2021-08-09 12:15 UTC, rhummelmose commented
@erankor This addition seems to do the trick to a large extent but a very important thing has to be changed. The internal caching behavior prevents the module from calling the upstream for getting the VOD map after the first time it has been resolved.
Looking into the implementation of the state machine that handles the meta data section I've been unable to identify a way to cleverly circumvent the cache, without adding a explicit conditional that I'm thinking must be there somewhere for handling of live already. It would be awesome if you could help out a bit.
Thanks!

2021-08-09 19:02 UTC, rhummelmose commented
Realized now after playing a little bit more with it, that it just hits the response cache, which is expected as I had it turned on. Turning it off makes it work perfectly.

2021-08-13 08:33 UTC, rhummelmose commented
@erankor Based on your feedback in #1297 I've implemented the above changes/additions.

Please have a look when time allows :)

2021-08-16 06:54 UTC, erankor commented
This change is problematic... if you will search the code for `media_set->type` you will see all the places that it will probably break. For example - dash_packager_write_mpd_period has a switch on this value, if `media_set->type` is MEDIA_SET_EVENT, it won't print the period header.
It may be better to avoid adding a new media_set type and instead just add some flag that will make the module output the tag you want. You can still use the existing type field in the JSON to relay this info (I mean - it won't be a new property on the JSON), just enable the flag + set the type to MEDIA_SET_LIVE.
The main point is - 99% of the code doesn't care if it's an event, it just cares if it's live/vod, so I think it's better to avoid touching all these places.

2021-08-16 17:40 UTC, rhummelmose commented
@erankor thanks, I'll revise

2021-08-16 18:45 UTC, rhummelmose commented
@erankor please let me know if it wasn't exactly what you had in mind, thanks again :)

2021-08-31 14:44 UTC, rhummelmose commented
@erankor friendly bump :) I have this branch running in production now and it works perfectly. Please have a look when you have the time.

2021-09-02 08:01 UTC, erankor requested changes

2021-09-02 08:01 UTC, erankor commented on vod/media_set_parser.c
> +			// because it ensures that incomplete segments are not included in the resulting playlist
I don't think it's about incomplete segments, it's about the fact we are not allowed to remove segments from the head of the media playlist when the type is event

2021-09-03 11:32 UTC, rhummelmose commented on vod/media_set.h
> +	bool_t set_event_playlist_type;			// causes HLS playlist type to be event and infinite live_window_duration
Agreed

2021-09-03 11:36 UTC, rhummelmose commented on README.md
> +* `playlistType` - string, can be set to `live`, `vod` or `event` (only supported or HLS playlists), default is `vod`.
Thanks

2021-09-03 12:23 UTC, rhummelmose commented on vod/hls/m3u8_builder.c
> +#define M3U8_HEADER_EVENT "#EXT-X-PLAYLIST-TYPE:EVENT\n"
Yes, I've made it calculate that part of the result_size based on the playllist type

2021-09-03 12:27 UTC, rhummelmose commented on vod/media_set_parser.c
> +		if (sequence->key_frame_durations != NULL && media_set->type == MEDIA_SET_VOD)
You're right

2021-09-03 12:38 UTC, rhummelmose commented on vod/media_set_parser.c
> +	result->set_event_playlist_type = params[MEDIA_SET_PARAM_PLAYLIST_TYPE] != NULL &&
Makes sense to make the normal case of VOD circumvent the rest of the code

2021-09-03 12:39 UTC, rhummelmose commented on vod/media_set_parser.c
> +				if ((result->type == MEDIA_SET_LIVE) &&
Yes sir

2021-09-03 13:08 UTC, rhummelmose reviewed
As requested

2021-09-05 06:52 UTC, erankor requested changes

2021-09-05 06:52 UTC, erankor commented on vod/hls/m3u8_builder.c
> +		playlist_type_header_size +
just use M3U8_HEADER_EVENT here, not trying to be exact (e.g. before the change, I always added vod, also in live)

2021-09-05 06:52 UTC, erankor commented on vod/media_set_parser.c
> +		if (params[MEDIA_SET_PARAM_PLAYLIST_TYPE] != NULL &&
no need to check params[MEDIA_SET_PARAM_PLAYLIST_TYPE] != NULL here, if we entered the 'else', it's surely not NULL

2021-09-05 06:52 UTC, erankor commented on vod/media_set_parser.c
> +		} else if (params[MEDIA_SET_PARAM_PLAYLIST_TYPE]->v.str.len != playlist_type_live.len ||
please add newline between the } and else, that is the convention here

2021-09-05 06:52 UTC, erankor commented on vod/media_set_parser.c
> +			// because we aren't allowed to remove segments from the head for this playlist type
move the comment a bit down, near if (!result->is_live_event)

2021-09-05 18:46 UTC, rhummelmose commented
Thanks @eranko, changes as requested :)

2021-09-07 14:14 UTC, merged

2021-09-07 14:15 UTC, erankor commented
Merged, thanks!

2021-09-07 17:55 UTC, rhummelmose commented
Epic!